config/routes.rb
Rubinbnb::Application.routes.draw do
  root to: 'bnb#home'

  match "/login", to: "bnb#login"
  match "/singup", to: "bnb#singup"
  match "/profile", to: "bnb#profile"
  match "/invites", to: "bnb#invites"      

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bnb_controller.rb
class BnbController < ApplicationController
  def home
  end

  def login
  end

  def singup
  end

  def profile
  end

  def invites
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bnb_helper.rb
module BnbHelper
end

app/views/bnb/home.html.erb
<div class="center hero-unit">
  <h1>Witaj w RubinBnB!</h1>

  <h2><a href="#">Rubin BnB</a> jest fejkowym system zaproszeń wykonanym w celu nauki RoR</h2>
  <%= link_to "Załóż konto!", '#', class: "btn btn-large btn-primary" %><br />
  <%= link_to "Zaproś znajmych z Facebooka", '#' %>
  <%= link_to "Zaproś znajmych poprzez Email", '#' %>      
</div>

app/views/bnb/invites.html.erb
<h1>Bnb#invites</h1>
<p>Find me in app/views/bnb/invites.html.erb</p>

app/views/bnb/login.html.erb
<h1>Bnb#login</h1>
<p>Find me in app/views/bnb/login.html.erb</p>

app/views/bnb/profile.html.erb
<h1>Bnb#profile</h1>
<p>Find me in app/views/bnb/profile.html.erb</p>

app/views/bnb/singup.html.erb
<h1>Bnb#singup</h1>
<p>Find me in app/views/bnb/singup.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
<div>STOPKA</div>
</footer>

app/views/layouts/_header.html.erb
  <header>
    <nav>
      <ul class="nav pull-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Zarejestruj się", singup_path %></li>
        <li><%= link_to "Logowanie", login_path %></li>
        <li><%= link_to "Profil", profile_path %></li>        
      </ul>
    </nav>  
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubinbnb</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>  
  <div class="container">  
<%= yield %>
  </div>
  <%= render 'layouts/footer' %>  
</body>
</html>